### ISSUE TITLE
.shy will not write file, xp, win 7

### ISSUE THREAD

**Issue by illeverbe** [shoes/shoes-deprecated#106]
# this works in shoes but will not write a file when packaged.

Shoes.app do  
    def write_file
        para "trying to write a file"  
        file_name = 'antler.rb'
        opf = File.open(file_name , 'w')  
        opf.puts "antler written"  
        opf.close  
    end
    write_file  
end

**Comment by steveklabnik** [comment]
Are you sure? Where are you checking for the file? Is there anything in the
Shoes console?

Also, writing antlr grammars in a shoes app? Fun!
On Jun 3, 2011 9:31 AM, "illeverbe" <
reply@reply.github.com>
wrote:

**Comment by illeverbe** [comment]
i am sure. Looked everywhere. Forgive me, but i don't know how to access console, unless errors automatically pop it up. But the window does pop up 'trying to write a file'. Works fine until 'packaged' (compiled?)

**Comment by steveklabnik** [comment]
The console is accessed by hitting either control-/ or alt-/, I forget which
on windows.

And how did you package it? As a shy, or as a full exe?

**Comment by illeverbe** [comment]
Console states 'Loaded SHY:...'. Packaged as a shy. Maybe you can tell me how to package as a 'full exe' ? Thanks for the prompt attention.

**Comment by steveklabnik** [comment]
Okay, but there are no other errors? That still makes me think it's getting written out somewhere, it'd throw an exception and it'd appear in the console otherwise.

Uhhh the package menu should have an option to build an exe. I don't remember off the top of my head for Windows, though, as I work mostly on the Mac, and packaging is terribly broken on it right now. :(

The packager is one of those fiddly bits of shoes that is mysterious and not well tested, so bug reports are great!

Could you try this for me? Instead of using a relative path like 'antler.rb,' could you make it a full path, to somewhere you know exists? Like

```
file_name = 'C:\Documents and Settings\whatever\something\antler.rb'
```

I don't know what your filesystem is set up to look like. But pick something. :) I feel like it's writing out the file, but somewhere strange.

If it's not, and there's no error message, I'm not sure how to help. :/

**Comment by illeverbe** [comment]
Cool beans!  that worked on win 7    :-)    Thanks much.

**Comment by steveklabnik** [comment]
Excellent. :)

**Comment by ashbb** [comment]
Shoes extracts .shy file under your `TEMP` directory. So, it will write a file, antler.rb, under TEMP.

Try out the following. ;-)

```
Shoes.app do
  def write_file
    para "trying to write a file"
    #file_name = 'antler.rb'
    file_name = ask_save_file
    opf = File.open(file_name , 'w')
    opf.puts "antler written"
    opf.close
  end
  write_file
end
```
