### ISSUE TITLE
Serialport crashes Shoes

### ISSUE THREAD

**Issue by ds1982** [shoes/shoes-deprecated#114]
Hi,

in my App i need to use the Ruby Serialport (http://ruby-serialport.rubyforge.org/).
Just the line "require 'serielport' "crashes Shoes with a Runtime Error.

Any Ideas?

Greets

DS

**Comment by steveklabnik** [comment]
The problem is that serialport is written as a C extension, and so the only way to get it to work currently is to build your own custom Shoes.

Sorry about that! Crashing is also degenerate behavior. I'm going to leave the ticket open, because we should at least not do that, that's kind of excessive.

**Comment by ds1982** [comment]
is there another way to use a com-Port in Shoes without the Serialport-Extension?

**Comment by steveklabnik** [comment]
I personally am not super familliar. Maybe someone else will know? I don't do work with serial ports.

**Comment by zzak** [comment]
Try looking here? 
http://librelist.com/browser//shoes/2010/10/1/including-gems-serialport/

**Comment by steveklabnik** [comment]
Wow, I have a short memory apparently.
