### ISSUE TITLE
arrow is not shown correctly

### ISSUE THREAD

**Issue by Tranquility** [shoes/shoes-deprecated#17]
with the default position only half of the arrow is shown. which itself is not a problem because if you specify a position above 0 its shown completely...but if you want to make it clickable you come into trouble because only a small part is clickable.

**Comment by atomicules** [comment]
Tranquility, what platform are you on. I've just tried the following on Windows:

```
Shoes.app do
@arrow = arrow(50,50,50)
@arrow.click { para "Yo!"}
end
```

The arrow seems to detect clicks in the lower half of the arrow-head (doesn't detect clicks in the tail). So when I move this to it's default position:

```
Shoes.app do
@arrow = arrow(0,0,50)
@arrow.click { para "Yo!"}
end
```

It still detected clicks, since the part that is visible is the part that detects clicks.

**Comment by Tranquility** [comment]
Year that's exactly the phenomenon I ment. The arrow should be completely clickable. I did a workaround by placing a rect element directly under the the arrow, which detects the clicks. But that's not a very nice solution.

**Comment by ashbb** [comment]
> I did a workaround by placing a rect element directly under the the arrow, which detects the clicks. But that's not a very nice solution.

How about this one? You can get the same effect a little bit easier. 

<pre><code>
Shoes.app do
  @arrow1 = image top: 50, left: 50, width: 50, height: 50 do
    arrow(25,25,50)
  end
  @arrow1.click { para "Yo!"}
end
</code></pre>
