### ISSUE TITLE
is there a way to install this windows without admin rights

### ISSUE THREAD

**Issue by rdthree** [shoes/shoes-deprecated#219]
Thanks so much for keeping shoes alive.  I'd like to use it portable at work, however I do not have rights to the C: drive.  Is there a way to install it portable or at least choose a different drive?

**Comment by PragTob** [comment]
Hi,
as far as I know you can download the installer and start it on your home pc with admin rights and then install it to a thumb drive. Then you could take that thumb drive with you and use it at work, although you'd have to use it from the command line specifying the full path since it won't be in the path and/or file associations of the other machine. 

Haven't tried it though. Any logic mistake in my plan? Any further ideas @ashbb ?

**Comment by rdthree** [comment]
OK, that makes sense.  I'll do that.  Thanks again for the hard work.

**Comment by PragTob** [comment]
Glad I could help - I'll close this for now. If you got any troubles just come back here then we'll reopen it =)
