### ISSUE TITLE
text_item.text= and text_item.replace() appending, not replacing text

### ISSUE THREAD

**Issue by shekibobo** [shoes/shoes-deprecated#98]
```
stack(:width => 200) do
  @exec_list = stack do
    title "Execution Queue", :size => 14
    @exec_lines = para "click button to load", :size => 9
    @file_button = button "Load Process List"
    @file_button.click do
      filename = ask_open_file
      @manager.set_exec_list filename
      # format output
      **@exec_lines.text =  @manager.exec_list.map {|p| "#{p.join ' '}\n"}** #each time I run this, the new text is appended
    end
  end
```

**Comment by steveklabnik** [comment]
I am almost sure this is not a bug with Shoes. It's probably in your implementation of `set_exec_list`.

If I set your line to `@exec_lines.text = "hey"`, it does not add it every time.

If you can boil this down to a smaller test case that lets me deubug it fully, I'll re-open. Since I can't see your application code, there's not much more I can do.

**Comment by shekibobo** [comment]
Wow, my bad.  You're right.  I wasn't resetting the list.  Thanks.

Joshua Kovach
